import 'dart:io';

import 'package:path/path.dart' as p;

/// Fails when the harness's agent-facing docs reference things the bricks
/// do not generate: file paths, project classes, or lint rules.
///
/// Agents treat these docs as ground truth, so a stale name (a removed
/// widget, a renamed exception, an old folder) turns into confidently
/// wrong code. Run from the repository root:
///   dart run tool/harness_check.dart
void main() {
  final docs = _harnessDocs();
  final generatedPaths = _generatedPaths();
  final declared = _declaredTypes();
  final lintRules = _lintRules();

  final problems = <String>[];
  final code = RegExp(r'`([^`\n]+)`');

  for (final doc in docs) {
    final rel = p.relative(doc.path);
    final lines = doc.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      for (final match in code.allMatches(lines[i])) {
        final token = match.group(1)!.trim();
        final where = '$rel:${i + 1}';

        // Lines that tell the agent to create something may name new paths.
        final proposes =
            RegExp(r'\b(propose|create|add)\b', caseSensitive: false)
                .hasMatch(lines[i]);
        final path = _asProjectPath(token);
        if (path != null && !proposes && !_pathExists(path, generatedPaths)) {
          problems.add('$where: path `$token` is not generated by any brick');
        }

        for (final name in RegExp(r'\b[A-Z][A-Za-z0-9]+\b')
            .allMatches(token)
            .map((m) => m.group(0)!)) {
          if (_isProjectTypeName(name) && !declared.contains(name)) {
            problems.add('$where: type `$name` is not declared in the bricks');
          }
        }

        final rule = RegExp(r'^(no_[a-z_]+|repo_transport_only)$')
            .firstMatch(token)
            ?.group(1);
        if (rule != null && !lintRules.contains(rule)) {
          problems.add('$where: lint rule `$rule` does not exist');
        }
      }
    }
  }

  if (problems.isEmpty) {
    print('Harness docs reference only generated paths, types and rules '
        '(${docs.length} files checked).');
    return;
  }
  for (final problem in problems) {
    print('::error::$problem');
  }
  exit(1);
}

List<File> _harnessDocs() {
  final root = Directory('bricks/harness/__brick__');
  return root
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .where((f) => !f.path.contains('${p.separator}.harness${p.separator}'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
}

/// Every path a generated project can contain, with brick template
/// placeholders (`{{feature_name.snakeCase()}}`) normalised to `<name>`.
Set<String> _generatedPaths() {
  final paths = <String>{};
  for (final brick in ['project', 'bloc', 'harness']) {
    final root = Directory('bricks/$brick/__brick__');
    for (final entity in root.listSync(recursive: true)) {
      var rel = p
          .relative(entity.path, from: root.path)
          .replaceAll(p.separator, '/')
          .replaceAll(RegExp(r'\{\{[^}]+\}\}'), '<name>');
      paths.add(rel);
      // Parent directories count too.
      while (rel.contains('/')) {
        rel = rel.substring(0, rel.lastIndexOf('/'));
        paths.add(rel);
      }
    }
  }
  // Generated at build/run time, not by mason.
  paths.addAll([
    '.harness/system-snapshot.md',
    'lib/l10n/generated',
    'l10n.yaml',
    'pubspec.yaml',
    'analysis_options.yaml',
  ]);
  return paths;
}

String? _asProjectPath(String token) {
  const roots = [
    'lib/',
    'test/',
    'scripts/',
    '.harness/',
    '.claude/',
    '.agents/',
    '.cursor/',
  ];
  if (!roots.any(token.startsWith)) return null;
  if (token.contains(' ') || token.contains('*')) return null;
  // Placeholders used in prose: <name>, <feature>, <component>, ...
  return token
      .replaceAll(RegExp(r'<[a-z_]+>'), '<name>')
      .replaceAll(RegExp(r'/$'), '');
}

bool _pathExists(String path, Set<String> generated) {
  if (generated.contains(path)) return true;
  // `lib/features/<name>/...` also matches the concrete showcase feature.
  final asShowcase = path.replaceFirst('features/<name>', 'features/showcase');
  return generated.contains(asShowcase);
}

/// Project-specific type names follow these conventions; Flutter/RxDart
/// types (Scaffold, BehaviorSubject, ...) are deliberately not checked.
bool _isProjectTypeName(String name) {
  const ignored = {
    'ApiException', // sealed base, declared
    'DioException', 'FormatException', 'TextEditingController',
    'StatefulWidget', 'StatelessWidget', 'ConsumerWidget', 'HookWidget',
    'StreamBuilder', 'PublishSubject', 'BehaviorSubject',
    'CompositeSubscription', 'RetryInterceptor', 'Http2Adapter',
    'CancelToken', 'ResponseType', 'Dio',
    'AppLocalizations', // generated by flutter gen-l10n
  };
  if (ignored.contains(name)) return false;
  return RegExp(
    r'^(App|Res|Api|Show|Common|Cancel|Persistence|Routes|Dio)\w*$|'
    r'\w+(Exception|Response|Action|Interceptor)$',
  ).hasMatch(name);
}

Set<String> _declaredTypes() {
  final names = <String>{'ApiException'};
  final decl = RegExp(
    r'\b(?:class|mixin|extension|enum|typedef)\s+([A-Z][A-Za-z0-9]*)',
  );
  for (final brick in ['project', 'bloc']) {
    for (final f in Directory('bricks/$brick/__brick__')
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))) {
      names.addAll(
        decl.allMatches(f.readAsStringSync()).map((m) => m.group(1)!),
      );
    }
  }
  // Third-party types the docs legitimately name.
  names.addAll(['RetryInterceptor', 'DioClient']);
  return names;
}

Set<String> _lintRules() {
  final dir = Directory('packages/redux_rxdart_lints/lib/src/rules');
  return dir
      .listSync()
      .whereType<File>()
      .expand((f) => RegExp(r"name: '([a-z_]+)'")
          .allMatches(f.readAsStringSync())
          .map((m) => m.group(1)!))
      .toSet();
}
