import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Fails when the harness's agent-facing docs reference things the bricks
/// do not generate (file paths, project classes, lint rules), or when the
/// skill suite is inconsistent (Agent Skills frontmatter, Claude Code entry
/// points, the `managed_skills` list that `upgrade.dart` relies on).
///
/// Agents treat these docs as ground truth, so a stale name (a removed
/// widget, a renamed exception, an old folder) turns into confidently
/// wrong code. Run from the repository root:
///   dart run tool/harness_check.dart
void main() {
  final docs = _harnessDocs();
  final generatedPaths = _generatedPaths();
  final declared = _declaredTypes();
  final lintRules = _lintRules();

  final problems = <String>[..._skillProblems(), ..._mustacheProblems()];
  final code = RegExp(r'`([^`\n]+)`');

  for (final doc in docs) {
    final rel = p.relative(doc.path);
    final lines = doc.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      for (final match in code.allMatches(lines[i])) {
        final token = match.group(1)!.trim();
        final where = '$rel:${i + 1}';

        // Lines that tell the agent to create something may name new paths.
        final proposes =
            RegExp(r'\b(propose|create|add)\b', caseSensitive: false)
                .hasMatch(lines[i]);
        final path = _asProjectPath(token);
        if (path != null && !proposes && !_pathExists(path, generatedPaths)) {
          problems.add('$where: path `$token` is not generated by any brick');
        }

        for (final name in RegExp(r'\b[A-Z][A-Za-z0-9]+\b')
            .allMatches(token)
            .map((m) => m.group(0)!)) {
          if (_isProjectTypeName(name) && !declared.contains(name)) {
            problems.add('$where: type `$name` is not declared in the bricks');
          }
        }

        final rule = RegExp(r'^(no_[a-z_]+|repo_transport_only)$')
            .firstMatch(token)
            ?.group(1);
        if (rule != null && !lintRules.contains(rule)) {
          problems.add('$where: lint rule `$rule` does not exist');
        }
      }
    }
  }

  if (problems.isEmpty) {
    print('Harness docs reference only generated paths, types and rules '
        '(${docs.length} files checked); skills are consistent.');
    return;
  }
  for (final problem in problems) {
    print('::error::$problem');
  }
  exit(1);
}

List<File> _harnessDocs() {
  final root = Directory('bricks/harness/__brick__');
  return root
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .where((f) => !f.path.contains('${p.separator}.harness${p.separator}'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
}

/// Every path a generated project can contain, with brick template
/// placeholders (`{{feature_name.snakeCase()}}`) normalised to `<name>`.
Set<String> _generatedPaths() {
  final paths = <String>{};
  for (final brick in ['project', 'bloc', 'harness']) {
    final root = Directory('bricks/$brick/__brick__');
    for (final entity in root.listSync(recursive: true)) {
      var rel = p
          .relative(entity.path, from: root.path)
          .replaceAll(p.separator, '/')
          .replaceAll(RegExp(r'\{\{[^}]+\}\}'), '<name>');
      paths.add(rel);
      // Parent directories count too.
      while (rel.contains('/')) {
        rel = rel.substring(0, rel.lastIndexOf('/'));
        paths.add(rel);
      }
    }
  }
  // Generated at build/run time, not by mason, or created by agents
  // following the harness skills.
  paths.addAll([
    '.harness/system-snapshot.md',
    '.harness/skills/<name>.md',
    '.harness/specs/<name>.md',
    'lib/l10n/generated',
    'l10n.yaml',
    'pubspec.yaml',
    'analysis_options.yaml',
  ]);
  return paths;
}

String? _asProjectPath(String token) {
  const roots = [
    'lib/',
    'test/',
    'scripts/',
    '.harness/',
    '.claude/',
    '.agents/',
    '.cursor/',
  ];
  if (!roots.any(token.startsWith)) return null;
  if (token.contains(' ') || token.contains('*')) return null;
  // Placeholders used in prose: <name>, <feature>, <component>, ...
  return token
      .replaceAll(RegExp(r'<[a-z_]+>'), '<name>')
      .replaceAll(RegExp(r'/$'), '');
}

/// `<name>` on either side stands for one path segment (or part of one):
/// `lib/features/<name>/` matches the showcase feature, and a concrete
/// `.harness/skills/build-ui.md` matches the agent-created pattern.
bool _pathExists(String path, Set<String> generated) {
  if (generated.contains(path)) return true;
  RegExp pattern(String withPlaceholders) => RegExp(
        '^${withPlaceholders.split('<name>').map(RegExp.escape).join('[^/]+')}\$',
      );
  if (path.contains('<name>') && generated.any(pattern(path).hasMatch)) {
    return true;
  }
  return generated
      .where((g) => g.contains('<name>'))
      .any((g) => pattern(g).hasMatch(path));
}

/// Project-specific type names follow these conventions; Flutter/RxDart
/// types (Scaffold, BehaviorSubject, ...) are deliberately not checked.
bool _isProjectTypeName(String name) {
  const ignored = {
    'ApiException', // sealed base, declared
    'DioException', 'FormatException', 'TextEditingController',
    'StatefulWidget', 'StatelessWidget', 'ConsumerWidget', 'HookWidget',
    'StreamBuilder', 'PublishSubject', 'BehaviorSubject',
    'CompositeSubscription', 'RetryInterceptor', 'Http2Adapter',
    'CancelToken', 'ResponseType', 'Dio',
    'AppLocalizations', // generated by flutter gen-l10n
    'AppBar', 'AppLifecycleListener', 'AppLifecycleState', // Flutter
  };
  if (ignored.contains(name)) return false;
  return RegExp(
    r'^(App|Res|Api|Show|Common|Cancel|Persistence|Routes|Dio)\w*$|'
    r'\w+(Exception|Response|Action|Interceptor)$',
  ).hasMatch(name);
}

Set<String> _declaredTypes() {
  final names = <String>{'ApiException'};
  final decl = RegExp(
    r'\b(?:class|mixin|extension|enum|typedef)\s+([A-Z][A-Za-z0-9]*)',
  );
  for (final brick in ['project', 'bloc']) {
    for (final f in Directory('bricks/$brick/__brick__')
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))) {
      names.addAll(
        decl.allMatches(f.readAsStringSync()).map((m) => m.group(1)!),
      );
    }
  }
  // Third-party types the docs legitimately name.
  names.addAll(['RetryInterceptor', 'DioClient']);
  return names;
}

/// Every `.agents/skills/<name>/SKILL.md` follows the Agent Skills format
/// (agentskills.io), has a Claude Code entry point with the same name and
/// description, and is listed in `.harness/version.json` → `managed_skills`
/// (what `upgrade.dart` replaces, and removes once no longer shipped).
List<String> _skillProblems() {
  const brick = 'bricks/harness/__brick__';
  final problems = <String>[];
  final agents = _skillDirs('$brick/.agents/skills');
  final claude = _skillDirs('$brick/.claude/skills');
  final validName = RegExp(r'^[a-z0-9]+(-[a-z0-9]+)*$');

  for (final name in agents) {
    final skill = File('$brick/.agents/skills/$name/SKILL.md');
    if (!skill.existsSync()) {
      problems.add('${skill.path}: missing');
      continue;
    }
    final meta = _frontmatter(skill);
    final description = meta['description'] ?? '';
    if (meta['name'] != name) {
      problems.add('${skill.path}: name "${meta['name']}" must equal the '
          'folder name "$name"');
    }
    if (name.length > 64 || !validName.hasMatch(name)) {
      problems.add('${skill.path}: name must be lowercase words joined by '
          'single hyphens, at most 64 characters');
    }
    if (description.isEmpty || description.length > 1024) {
      problems.add('${skill.path}: description must be 1-1024 characters '
          '(has ${description.length})');
    }

    final entry = File('$brick/.claude/skills/$name/SKILL.md');
    if (!entry.existsSync()) {
      problems.add('${entry.path}: missing Claude Code entry point');
      continue;
    }
    final entryMeta = _frontmatter(entry);
    if (entryMeta['name'] != meta['name'] ||
        entryMeta['description'] != description) {
      problems.add('${entry.path}: name and description must be identical '
          'to .agents/skills/$name/SKILL.md');
    }
    if (!entry.readAsStringSync().contains('.agents/skills/$name/SKILL.md')) {
      problems
          .add('${entry.path}: must point at .agents/skills/$name/SKILL.md');
    }
  }
  for (final orphan in claude.difference(agents)) {
    problems.add('$brick/.claude/skills/$orphan: no .agents/skills/$orphan');
  }

  final manifest = jsonDecode(
    File('$brick/.harness/version.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final managed = (manifest['managed_skills'] as List? ?? [])
      .map((e) => e.toString())
      .toList();
  final expected = agents.toList()..sort();
  if (managed.join(',') != expected.join(',')) {
    problems.add('$brick/.harness/version.json: managed_skills must list '
        'exactly the shipped skills, sorted: ${expected.join(', ')}');
  }
  return problems;
}

/// Mason renders every brick file as a mustache template: a tag such as
/// `'{{$key}}'` in a script or skill is silently rewritten (here to '') in
/// generated apps. Only the files meant to be templated may contain one.
List<String> _mustacheProblems() {
  const brick = 'bricks/harness/__brick__';
  const templated = {'AGENTS.md', 'CLAUDE.md', '.harness/version.json'};
  final tag = RegExp(r'\{\{[^{}]*\}\}');
  final problems = <String>[];
  for (final file
      in Directory(brick).listSync(recursive: true).whereType<File>()) {
    final rel = p.relative(file.path, from: brick).replaceAll(p.separator, '/');
    if (templated.contains(rel)) continue;
    final lines = file.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      final m = tag.firstMatch(lines[i]);
      if (m != null) {
        problems.add('${file.path}:${i + 1}: `${m.group(0)}` is a mustache '
            'tag; mason rewrites it in generated apps');
      }
    }
  }
  return problems;
}

Set<String> _skillDirs(String root) {
  final dir = Directory(root);
  if (!dir.existsSync()) return {};
  return dir
      .listSync()
      .whereType<Directory>()
      .map((d) => p.basename(d.path))
      .toSet();
}

/// Single-line `key: value` pairs between the leading `---` fences.
Map<String, String> _frontmatter(File file) {
  final lines = file.readAsLinesSync();
  if (lines.isEmpty || lines.first.trim() != '---') return {};
  final meta = <String, String>{};
  for (final line in lines.skip(1)) {
    if (line.trim() == '---') break;
    final m = RegExp(r'^([a-z_-]+):\s*(.*)$').firstMatch(line);
    if (m != null) meta[m.group(1)!] = m.group(2)!.trim();
  }
  return meta;
}

Set<String> _lintRules() {
  final dir = Directory('packages/redux_rxdart_lints/lib/src/rules');
  return dir
      .listSync()
      .whereType<File>()
      .expand((f) => RegExp(r"name: '([a-z_]+)'")
          .allMatches(f.readAsStringSync())
          .map((m) => m.group(1)!))
      .toSet();
}
