// ignore_for_file: avoid_print

import 'dart:io';

/// Writes `.harness/system-snapshot.md`: a compact, deterministic map of
/// the project for AI agents, so they don't re-scan the tree every session.
///
/// Deterministic on purpose (no timestamps, no git log, no analyzer run):
/// the file only changes when the project's shape changes, so it can be
/// committed without creating noise. Never edit it by hand.
void main() {
  final out = StringBuffer()
    ..writeln('# Project Snapshot')
    ..writeln()
    ..writeln('<!-- Generated by scripts/agent/snapshot.dart. Do not edit. -->')
    ..writeln();

  _section(out, 'Features (lib/features/)', _features());
  _section(out, 'Routes (lib/utils/router/routes.dart)', _routes());
  _section(
    out,
    'API endpoints (lib/networking/api_constants.dart)',
    _endpoints(),
  );
  _section(out, 'Redux AppState fields', _appStateFields());
  _section(out, 'Direct dependencies', _dependencies());

  final file = File('.harness/system-snapshot.md');
  final content = out.toString();
  if (file.existsSync() && file.readAsStringSync() == content) {
    print('Snapshot unchanged.');
    return;
  }
  file
    ..createSync(recursive: true)
    ..writeAsStringSync(content);
  print('Snapshot written to ${file.path}.');
}

void _section(StringBuffer out, String title, List<String> lines) {
  out.writeln('## $title');
  out.writeln(lines.isEmpty ? '_None._' : lines.join('\n'));
  out.writeln();
}

List<String> _features() {
  final dir = Directory('lib/features');
  if (!dir.existsSync()) return [];
  final names =
      dir
          .listSync()
          .whereType<Directory>()
          .map((d) => d.uri.pathSegments.where((s) => s.isNotEmpty).last)
          .toList()
        ..sort();
  return [
    for (final name in names)
      '- `$name`'
          '${Directory('test/features/$name').existsSync() ? '' : ' (no tests)'}',
  ];
}

List<String> _routes() {
  final file = File('lib/utils/router/routes.dart');
  if (!file.existsSync()) return [];
  return RegExp(r"static const String (\w+) = '([^']+)';")
      .allMatches(file.readAsStringSync())
      .map((m) => '- `${m[1]}` → `${m[2]}`')
      .toList();
}

List<String> _endpoints() {
  final file = File('lib/networking/api_constants.dart');
  if (!file.existsSync()) return [];
  return RegExp(
        r'^\s*static\s+(?:const\s+)?String\s+(?:get\s+)?(\w+)',
        multiLine: true,
      )
      .allMatches(file.readAsStringSync())
      .map((m) => m[1]!)
      .where((n) => n != 'baseUrl')
      .map((n) => '- `ApiConstants.$n`')
      .toList();
}

List<String> _appStateFields() {
  final file = File('lib/redux/app_state.dart');
  if (!file.existsSync()) return [];
  return RegExp(r'^\s*final\s+([\w<>?, ]+?)\s+(\w+);', multiLine: true)
      .allMatches(file.readAsStringSync())
      .map((m) => '- `${m[2]}`: `${m[1]}`')
      .toList();
}

List<String> _dependencies() {
  final file = File('pubspec.yaml');
  if (!file.existsSync()) return [];
  final lines = file.readAsLinesSync();
  final start = lines.indexWhere((l) => l.trim() == 'dependencies:');
  if (start == -1) return [];
  final deps = <String>[];
  for (final line in lines.skip(start + 1)) {
    if (line.isNotEmpty && !line.startsWith(' ')) break;
    final m = RegExp(r'^  ([a-z_][a-z0-9_]*):\s*(\S*)').firstMatch(line);
    if (m != null && m[2]!.isNotEmpty && !m[2]!.startsWith('#')) {
      deps.add('${m[1]} ${m[2]}');
    }
  }
  return deps.isEmpty ? [] : [deps.join(', ')];
}
